#!/bin/bash

docker build -t compile .

docker run \
    --init \
    --net foo \
    --name compile \
    --rm \
    -v ~/.cache/Tangle:/.cache \
    -v ~/Tangle/contracts:/app/contracts:ro \
    -v ~/Tangle/containers/test/pipe:/app/containers/compile/test \
    -it \
    compile