#!/bin/bash

docker build -t yankeefootball .

docker run \
    --net foo \
    --name YankeeFootball \
    --rm \
    -v ~/Tangle/testing/HelpfulCandlewax:/app/HelpfulCandlewax:ro \
    -it \
    yankeefootball