#!/bin/sh

address=$( (echo ''; echo '') | geth --verbosity 1 account new | sed -nr 's/.*0x(.*)/\1/p' )
sed -i "s/\"chainId\": 0/\"chainId\": $chainid/" genesis.json
sed -i "s/ADDRESS/$address/" genesis.json
geth init genesis.json > /dev/null 2&>1
geth \
    --maxpeers 0 \
    --nodiscover \
    --mine \
    --miner.threads 1 \
    --miner.etherbase $address \
    --http \
    --http.api eth,web3,net,debug,personal \
    --http.corsdomain "*" \
    --http.addr "0.0.0.0" \
    --http.vhosts "*" \
    --ws \
    --ws.api eth,web3,net,debug,personal \
    --ws.addr "0.0.0.0" \
    --ws.origins "*" \
    --txpool.pricelimit 0 \
    --miner.gasprice 0 \
    --allow-insecure-unlock \
    --unlock $address \
    --password <('') > /dev/null 2&>1 &
./execpipe
