#!/bin/sh

home=/home/bradbrown

error=$(cat compile.json | \
solc --allow-paths $home/ERC20,$home/Farmable,$home/GentleMidnight \
    --standard-json | \
jq -Mc '..|.formattedMessage?|strings' | tr -d '"' | sed -z '$ s/\n$//')
[ -z $error ] && echo Compilation successful!
echo $error | sed -z '$ s/\n$//'