#!/bin/bash

tar -cf - -C ~/Tangle \
    json \
    containers/ui | \
docker build -t ui -f containers/ui/Dockerfile -

docker run \
    --init \
    --net host \
    --name ui \
    --rm \
    -v ~/.config:/root/.config \
    -v ~/.secret/bradbrownllc-tngl-6f28aeff09d5.json:/ui/app/bradbrownllc-tngl-6f28aeff09d5.json \
    -v ~/Tangle/containers/ui/web/index.html:/ui/web/index.html \
    -v ~/Tangle/containers/ui/web/vite.config.ts:/ui/web/vite.config.ts \
    -v ~/Tangle/containers/ui/web/src:/ui/web/src \
    -v ~/Tangle/containers/ui/web/public:/ui/web/public \
    -v ~/Tangle/json/tngl.json:/ui/web/src/components/tngl.json \
    -v ~/Tangle/json/chains.json:/ui/web/src/components/chains.json \
    -it \
    ui \
    /bin/bash -c "vite build; cd ../app; tsc; gcloud app deploy -q"