#!/bin/sh

case $1 in
tangle) echo \
    /app/contracts \
    lib/compile2.mjs ;;
weth) echo \
    /app/WETH \
    json/weth.json ;;
factory) echo \
    /app/v2-periphery \
    /app/v2-core \
    json/factory.json ;;
router) echo \
    /app/v2-periphery \
    /app/v2-core \
    /app/solidity-lib \
    json/router.json ;;
esac