#!/bin/bash

docker build -t hurtfulbeanstalk .

docker run \
    --init \
    --net foo \
    --name HurtfulBeanstalk \
    --rm \
    -v ~/Tangle/testing/HelpfulCandlewax:/app/HelpfulCandlewax:ro \
    -it \
    hurtfulbeanstalk