#!/bin/bash

docker build -t varianteddy .

docker run \
    --net foo \
    --name VariantEddy \
    --rm \
    -v ~/ERC20:/app/ERC20:ro \
    -v ~/Farmable:/app/Farmable:ro \
    -v ~/GentleMidnight:/app/GentleMidnight:ro \
    -v ~/Tangle:/app/Tangle:ro \
    -v ~/Uniswap:/app/Uniswap:ro \
    -v ~/HelpfulCandlewax:/app/HelpfulCandlewax \
    -it \
    varianteddy