#!/bin/bash

docker build -t varianteddy .

docker run \
    --init \
    --net foo \
    --name VariantEddy \
    --rm \
    -v ~/Tangle/contracts:/app/Tangle/contracts \
    -v ~/Tangle/compile:/app/Tangle/compile \
    -v ~/Tangle/testing/HelpfulCandlewax:/app/HelpfulCandlewax \
    -v ~/Tangle/testing/tmp:/app/tmp \
    -v ~/Uniswap:/app/Uniswap \
    -it \
    varianteddy