#!/bin/bash

docker build -t yankeefootball .

docker run \
    --net foo \
    --name YankeeFootball \
    --rm \
    -v /home/bradbrown/HelpfulCandlewax:/app/HelpfulCandlewax:ro \
    -it \
    yankeefootball