#!/bin/bash

docker build -t ui2 .

docker run \
    --init \
    --net host \
    --name ui2 \
    --rm \
    -v ~/Tangle/containers/ui2/src/classes:/app/app/src/classes \
    -v ~/Tangle/containers/ui2/src/components:/app/app/src/components \
    -v ~/Tangle/containers/ui2/src/routes:/app/app/src/routes \
    -v ~/Tangle/containers/ui2/src/stores:/app/app/src/stores \
    -v ~/Tangle/containers/ui2/src/theme:/app/app/src/theme \
    -v ~/Tangle/containers/ui2/src/app.d.ts:/app/app/src/app.d.ts \
    -v ~/Tangle/containers/ui2/src/app.html:/app/app/src/app.html \
    -v ~/Tangle/json:/app/app/src/json \
    -it \
    ui2