#!/bin/bash

docker build -t tangyscrap .

docker run \
    --init \
    --net foo \
    --name TangyScrap \
    --rm \
    -v ~/Tangle/testing/HelpfulCandlewax:/app/HelpfulCandlewax:ro \
    -v ~/Tangle/testing/tmp:/app/tmp \
    -it \
    tangyscrap